### ISSUE TITLE
Un-blurred image is seen before rendered version - or never blurs

### ISSUE THREAD

**Issue by kosso** [benbahrenburg/Ti.BlurView#20]
Hi Ben!
Firstly thanks for these modules.  Lifesaver! (and Android on too!)  Nice work - as usual! 

I'm using basicBlur with remote images (for a nice music artwork background in a music app I'm building) and I've found that I can see the un-blurred image on screen before the rendered version.  Sometimes, the blurred version doesn't load at all, so I added a 'load' event to apply the blurRadius then. While this fixes the blur, it doesn't solve the visible un-rendered version. 

Any way around this? Or a fix? ( I'd rather not have to locally cache the image then try the other blur methods. But if that's the only way... )

The Android version is working perfectly. 

Cheers!
Kosso

ps: Worth noting somewhere that blurring cannot be triggered while an app is in the background. It will cause a crash. OpenGL ES doesn't like it! ;)  [see : https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ImplementingaMultitasking-awareOpenGLESApplication/ImplementingaMultitasking-awareOpenGLESApplication.html ]

**Comment by benbahrenburg** [comment]
The module is really designed to blur images which are local. Because of that we have a 200 ms retry that is only performed once.  You can extend this using setBlurImageWait (property or method) to set this to whatever you want.  I added to beta 31 setBlurImageRetries (property or method) which allows you to retry this for a larger number of times. Give that a try and see if that helps resolve your issues.

**Comment by kosso** [comment]
Cheers Ben. I had a poke around the source code to see what I could do. ;)

For now on iOS, I set the opacity to 0, then set the image, then (re)apply the blurRadius in the 'load' event, then animate the opacity back in.  Suits my purpose for now.  But thanks for the pointers.
